name: chromedp
on:
  push:
    branches:
      - monorepo
    paths:
      - 'chromedp/**'
      - '.github/workflows/chromedp.yml'
defaults:
  run:
    working-directory: chromedp
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Packages
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y build-essential
      - name: Cache go modules
        uses: actions/cache@v2
        env:
          cache-name: cache-go-modules-casbin
        with:
          path: vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
      - name: Install Dependencies
        run: go mod download
      - name: Test
        run: |
          TMPDIR=$RUNNER_TEMP go test -v ./...
          chmod +x ./scripts/docker-test.sh
          ./scripts/docker-test.sh
