name: gogit
on:
  push:
    branches:
      - monorepo
    paths:
      - 'go-git/**'
      - '.github/workflows/gogit.yml'
defaults:
  run:
    working-directory: go-git
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache go modules
        uses: actions/cache@v2
        env:
          cache-name: cache-go-modules-gogit
        with:
          path: vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
      - name: Install Dependencies
        run: go mod download
      - name: Test
        run: go test -v .
